### ISSUE TITLE
custom domain name

### ISSUE THREAD

**Issue by pfaendtner** [UWPRG/UWPRG.github.io#37]
@anotherjoshsmith the custom domain name setup for prg.washington.edu should be working ( UW is forwarding it to UWprg.github.io (https://help.github.com/articles/quick-start-setting-up-a-custom-domain/) but it is not. UWIT says it is something on our end. any ideas?

**Comment by anotherjoshsmith** [comment]
I'm not sure what the problem is, I've never tried forwarding to a custom domain. I'll figure it out.

**Comment by anotherjoshsmith** [comment]
@pfaendtner looks like you already added the CNAME file, and using the dig command I can see that UWIT has also linked to the website with a CNAME record. 

`dig prg.washington.edu +nostats +nocomments +nocmd`

Looks like there's a placeholder "Under Construction" page at `prg.washington.edu` right now, so I'm not sure if the forwarding has been temporarily stopped. Did UWIT give you any hints about how to fix it, or have you contacted them again since adding the CNAME file to our repo?

**Comment by pfaendtner** [comment]
I gave this shit up
